/* ADICIONANDO DADOS */

INSERT INTO CLIENTE VALUES (NULL, "Roberto");
INSERT INTO CLIENTE VALUES (NULL, "Carlos");
INSERT INTO CLIENTE VALUES (NULL, "Manuel");
INSERT INTO CLIENTE VALUES (NULL, "André");
INSERT INTO CLIENTE VALUES (NULL, "Aline");
INSERT INTO CLIENTE VALUES (NULL, "Ana");
INSERT INTO CLIENTE VALUES (NULL, "Marcos");
INSERT INTO CLIENTE VALUES (NULL, "Maria");
INSERT INTO CLIENTE VALUES (NULL, "Ingrid");
INSERT INTO CLIENTE VALUES (NULL, "Vitor");

INSERT INTO TELEFONE VALUES (NULL, "34862387", 1);
INSERT INTO TELEFONE VALUES (NULL, "32745621", 2);
INSERT INTO TELEFONE VALUES (NULL, "34862387", 2);
INSERT INTO TELEFONE VALUES (NULL, "30944545", 5);
INSERT INTO TELEFONE VALUES (NULL, "29927364", 6);
INSERT INTO TELEFONE VALUES (NULL, "28673487", 7);
INSERT INTO TELEFONE VALUES (NULL, "31934753", 7);

INSERT INTO CARRO VALUES (NULL, "Ka", "Ford", 1);
INSERT INTO CARRO VALUES (NULL, "Fusca", "Ford", 2);
INSERT INTO CARRO VALUES (NULL, "Fiesta", "Ford", 3);
INSERT INTO CARRO VALUES (NULL, "ASX", "Mitsubishi", 4);
INSERT INTO CARRO VALUES (NULL, "HB20", "Hyundai", 5);
INSERT INTO CARRO VALUES (NULL, "Gol", "Volkswagen", 6);
INSERT INTO CARRO VALUES (NULL, "Hilux", "Toyota", 7);
INSERT INTO CARRO VALUES (NULL, "Amarok", "Volkswagen", 8);
INSERT INTO CARRO VALUES (NULL, "Outlander", "Volkswagen", 9);
INSERT INTO CARRO VALUES (NULL, "Tracker", "Chevrolet", 10);

INSERT INTO COR VALUES (NULL, "Branco");
INSERT INTO COR VALUES (NULL, "Preto");
INSERT INTO COR VALUES (NULL, "Azul");
INSERT INTO COR VALUES (NULL, "Vermelho");
INSERT INTO COR VALUES (NULL, "Cinza");
INSERT INTO COR VALUES (NULL, "Rosa");
INSERT INTO COR VALUES (NULL, "Verde");

INSERT INTO CARRO_COR VALUES (1, 5);
INSERT INTO CARRO_COR VALUES (2, 2);
INSERT INTO CARRO_COR VALUES (3, 1);
INSERT INTO CARRO_COR VALUES (4, 1);
INSERT INTO CARRO_COR VALUES (5, 2);
INSERT INTO CARRO_COR VALUES (5, 5);
INSERT INTO CARRO_COR VALUES (6, 5);
INSERT INTO CARRO_COR VALUES (7, 1);
INSERT INTO CARRO_COR VALUES (8, 2);
INSERT INTO CARRO_COR VALUES (9, 3);
INSERT INTO CARRO_COR VALUES (9, 2);
INSERT INTO CARRO_COR VALUES (10, 2);