/* CRIAÇÃO DAS TABELAS */

CREATE TABLE CLIENTE (
	ID_CLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL
);

CREATE TABLE TELEFONE (
	ID_TELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	NUMERO VARCHAR(10),
	ID_CLIENTE INT
);

CREATE TABLE CARRO (
	ID_CARRO INT PRIMARY KEY AUTO_INCREMENT,
	MODELO VARCHAR(30) NOT NULL,
	MARCA VARCHAR(30) NOT NULL,
	ID_CLIENTE INT UNIQUE
);

CREATE TABLE COR (
	ID_COR INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL
);

CREATE TABLE CARRO_COR (
	ID_CARRO INT,
	ID_COR INT,
	PRIMARY KEY (ID_CARRO, ID_COR)
);

/* ADIÇÃO DE CONSRAINTS */

ALTER TABLE TELEFONE
ADD CONSTRAINT FK_TELEFONE_CLIENTE
FOREIGN KEY (ID_CLIENTE)
REFERENCES CLIENTE(ID_CLIENTE);

ALTER TABLE CARRO
ADD CONSTRAINT FK_CARRO_CLIENTE
FOREIGN KEY (ID_CLIENTE)
REFERENCES CLIENTE(ID_CLIENTE);

ALTER TABLE CARRO_COR
ADD CONSTRAINT FK_CARRO
FOREIGN KEY (ID_CARRO)
REFERENCES CARRO(ID_CARRO);

ALTER TABLE CARRO_COR
ADD CONSTRAINT FK_COR
FOREIGN KEY (ID_COR)
REFERENCES COR(ID_COR);